# site settings
title: Elena Cebadera
subtitle: Elena Cebadera - UX/Product Designer
email: elena.cebadera@gmail.com
description: Elena Cebadera - UX/Product Designer
baseurl: "/porfolio3" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 
city: Valencia
state: 
zip_code: 
country: Spain
phone: (+34) 649 14 98 40

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/ele_tirorii/
linkedin_url: https://www.linkedin.com/in/elenacebadera/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/eletirorii

# build settings
markdown: kramdown

sass:
  style: compressed
